package ESharing.Shared.Util;

public enum Verifications {
    USER_NOT_EXIST,
    INVALID_USERNAME,
    INVALID_PASSWORD,
    INVALID_PHONE_NUMBER,
    INVALID_CITY,
    INVALID_NUMBER,
    INVALID_POSTAL_CODE,
    INVALID_STREET,
    NOT_THE_SAME_PASSWORDS,
    DATABASE_CONNECTION_ERROR
}
