package ESharing.Shared.Util;

public enum Views {
    WELCOME_VIEW,
    SIGN_IN_VIEW,
    SIGN_UP_VIEW,
    MAIN_APP_VIEW,
    MAIN_USER_SETTING_VIEW,
    FAILED_CONNECTION_VIEW,
    USER_ADDRESS_SETTING_VIEW,
    USER_INFO_SETTING_VIEW,
    RULES_VIEW;
}
